### PR TITLE
Added testing example for a request and moved paths constant to separate file

### PR DESCRIPTION
**Pull request by rdelfin**

### CODE REVIEW

**Comment by rdelfin** [comment]
@vpineda1996 Contains that thing

**Comment by rdelfin** [comment]
...shit this doesn't compile. Juait

**Comment by rdelfin** [comment]
Ok! Fixed

**Comment by vpnda** [comment]
well without this crap nothing works so i guess there's no way of screwing it more soooo

**Review by vpnda — APPROVED** [review]

**Comment by rdelfin** [comment]
WOOOO in-time fixes

**Pull request merged**
